services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 5555:5555
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vaccine_portal
      MYSQL_USER: thanghq
      MYSQL_PASSWORD: M@tkh@u1999
    volumes:
      - /var/lib/mysql:/var/lib/mysql
