version: '3.4'

services:
  api:
    user: root
    container_name: vaccine-portal-api
    build: .
    env_file:
      - .env.docker
    # command: npm run start
    ports:
      - 5556:5556
    depends_on:
      - mysql-db
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vaccine_portal
      MYSQL_USER: thanghq
      MYSQL_PASSWORD: M@tkh@u1999
    volumes:
      - mysql-vaccine-portal-volume:/var/lib/mysql
volumes:
  mysql-vaccine-portal-volume:
