version: '3.4'

services:
  api:
    user: root
    container_name: vaccine-portal-api
    build: .
    env_file:
      - .env
    ports:
      - 5556:5556
    depends_on:
      - mysql-db
      - redis-db
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysql-vaccine-portal-volume:/var/lib/mysql
  redis-db:
    container_name: redis-db
    image: redis/redis-stack-server:latest
    restart: always
    command: redis-server --save 20 1 --requirepass ${REDIS_QUEUE_PASSWORD}
    volumes:
      - redis-volume:/data
volumes:
  mysql-vaccine-portal-volume:
  redis-volume:
    driver: local
