version: '3.4'

services:
  api:
    container_name: vaccine-portal-api-dev
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.docker.dev
    command: npm run start:dev
    ports:
      - 5556:5556
    depends_on:
      - mysql-db-dev
      - redis-db-dev
  mysql-db-dev:
    container_name: mysql-db-dev
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysql-vaccine-portal-volume-dev:/var/lib/mysql
  redis-db-dev:
    container_name: redis-db
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --requirepass ${REDIS_QUEUE_PASSWORD}
    volumes:
      - redis-volume-dev:/data
volumes:
  mysql-vaccine-portal-volume-dev:
  redis-volume-dev:
    driver: local
